
# Load libraries ----------------------------------------------------------

#use library function to call the packages
library(tidyverse)
library(readxl)
library(broom)
library(gridExtra)
library(mgcv)


# Import data -------------------------------------------------------------

#set wd
setwd("yourpath/rgb") #set your own path

#import data
df10 = read_csv("bc007_rgb_curated.csv")


# data wrangling ----------------------------------------------------------

#relevel genotypes
df10$genotype = factor(df10$genotype, levels = c("Col-0", "lacs", "cyp"))

#Rename clusters
df10$cluster = factor(df10$cluster, levels = c("Healthy", "Chlorotic", "Necrotic"))

#model symptomatic size with gams

# create a leaf_id column for modelling
df11 = df10 %>%
  unite(col = "leaf_id", tray, pos, sep = "_", remove = F) %>%
  mutate_at(.vars = vars(leaf_id), .funs = funs(factor))%>%
  droplevels() %>% 
  mutate(size = size + 0.000001) # add a small value to prevent model missbehaving in those with lot of zeroes.

# create dataframe for healthy pixels only
df11_hl = df11 %>%
  filter(cluster == "Healthy") %>%
  mutate_at(.vars = vars(leaf_id), .funs = funs(factor))%>%
  droplevels()

# create dataframe for necrotic pixels only
df11_nc = df11 %>%
  filter(cluster == "Necrotic") %>%
  mutate_at(.vars = vars(leaf_id), .funs = funs(factor))%>%
  droplevels()

# create dataframe for chlorotic pixels only
df11_cl = df11 %>%
  filter(cluster == "Chlorotic") %>%
  mutate_at(.vars = vars(leaf_id), .funs = funs(factor))%>%
  droplevels() 


# Fit models --------------------------------------------------------------

# fit gam model with and without adding the genotype term to healthy pixels dataframe
m.g.h.0 = gam(size ~ s(hpi, k = 4) + s(hpi, leaf_id, bs = "re"), data = df11_hl, family = "betar")
m.g.h.1 = gam(size ~ s(hpi, by = genotype, k = 4) + s(hpi, leaf_id, bs = "re") + genotype, data = df11_hl, family = "betar")

# fit gam model with and without adding the genotype term to chlorotic pixels dataframe
m.g.c.0 = gam(size ~ s(hpi, k = 4) + s(hpi, leaf_id, bs = "re"), data = df11_cl, family = "betar")
m.g.c.1 = gam(size ~ s(hpi, by = genotype, k = 4) + s(hpi, leaf_id, bs = "re") + genotype, data = df11_cl, family = "betar")

# fit gam model with and without adding the genotype term to necrotic pixels dataframe
m.g.n.0 = gam(size ~ s(hpi, k = 4) + s(hpi, leaf_id, bs = "re"), data = df11_nc, family = "betar")
m.g.n.1 = gam(size ~ s(hpi, by = genotype, k = 4) + s(hpi, leaf_id, bs = "re") + genotype, data = df11_nc, family = "betar")


# extract predicted values ------------------------------------------------
#Healthy
newdata = df11_hl %>% 
  select(hpi, genotype, leaf_id) %>%
  filter(hpi == 0) %>%
  select(-hpi) %>% 
  slice(rep(row_number(), 31)) %>%
  mutate(hpi = rep(seq(0,96,3.2), each = 36))

#predict data
prd.h = predict.gam(m.g.h.1, newdata = newdata, se.fit = T,  exclude = "s(hpi, leaf_id)", type = "response")

#bind predicted data to newdata
prd.h2 = newdata

prd.h2$size_prd = prd.h$fit
prd.h2$se = prd.h$se.fit

#summarize to remove repeated data generated by omitting and calculate confidence intervals
prd.h3 = prd.h2 %>%
  group_by(hpi, genotype) %>%
  summarize(size = mean(size_prd), se = mean(se)) %>%
  mutate(up = size + se*1.96, low = size - se*1.96) %>%
  arrange(genotype)

#Relevel col-0 as the first factor level
prd.h3$genotype = relevel(prd.h3$genotype, "Col-0")

#Chlorotic
newdata = df11_cl %>% 
  select(hpi, genotype, leaf_id) %>%
  filter(hpi == 0) %>%
  select(-hpi) %>% 
  slice(rep(row_number(), 31)) %>%
  mutate(hpi = rep(seq(0,96,3.2), each = 36))

#predict data
prd.c = predict.gam(m.g.c.1, newdata = newdata, se.fit = T,  exclude = "s(hpi, leaf_id)", type = "response")

#bind predicted data to newdata
prd.c2 = newdata

prd.c2$size_prd = prd.c$fit
prd.c2$se = prd.c$se.fit

#summarize to remove repeated data generated by omitting and calculate confidence intervals
prd.c3 = prd.c2 %>%
  group_by(hpi, genotype) %>%
  summarize(size = mean(size_prd), se = mean(se)) %>%
  mutate(up = size + se*1.96, low = size - se*1.96) %>%
  arrange(genotype)

#Relevel col-0 as the first factor level
prd.c3$genotype = relevel(prd.c3$genotype, "Col-0")

#Necrotic
newdata = df11_nc %>% 
  select(hpi, genotype, leaf_id) %>%
  filter(hpi == 0) %>%
  select(-hpi) %>% 
  slice(rep(row_number(), 31)) %>%
  mutate(hpi = rep(seq(0,96,3.2), each = 36))

#predict data
prd.n = predict.gam(m.g.n.1, newdata = newdata, se.fit = T,  exclude = "s(hpi, leaf_id)", type = "response")

#bind predicted data to newdata
prd.n2 = newdata


prd.n2$size_prd = prd.n$fit
prd.n2$se = prd.n$se.fit

#summarize to remove repeated data generated by omitting and calculate confidence intervals
prd.n3 = prd.n2 %>%
  group_by(hpi, genotype) %>%
  summarize(size = mean(size_prd), se = mean(se)) %>%
  mutate(up = size + se*1.96, low = size - se*1.96) %>%
  arrange(genotype)

#Relevel col-0 as the first factor level
prd.n3$genotype = relevel(prd.n3$genotype, "Col-0")



# Final plot --------------------------------------------------------------

p.rgb.1 = prd.h3 %>%
  ggplot(aes_string("hpi", "size", ymin = "low", ymax = "up", color = "genotype", fill = "genotype"))+
  scale_x_continuous(breaks = c(0,24,48,72,96))+
  geom_line(size = 2)+
  geom_ribbon(alpha = 0.3, color = NA)+
  theme_bw()+
  labs(y = "Chlorotic pixel proportion", x = "Hours post infection")+
  theme(legend.position=c(0.12, 0.3),legend.title=element_text(size=14),
        legend.background = element_blank(),
        legend.box.background = element_blank())

p.rgb.2 = prd.c3 %>%
  ggplot(aes_string("hpi", "size", ymin = "low", ymax = "up", color = "genotype", fill = "genotype"))+
  scale_x_continuous(breaks = c(0,24,48,72,96))+
  geom_line(size = 2)+
  geom_ribbon(alpha = 0.3, color = NA)+
  theme_bw()+
  labs(y = "Chlorotic pixel proportion", x = "Hours post infection")+
  theme(legend.position=c(0.12, 0.75),legend.title=element_text(size=14),
        legend.background = element_blank(),
        legend.box.background = element_blank())

p.rgb.3 = prd.n3 %>%
  ggplot(aes_string("hpi", "size", ymin = "low", ymax = "up", color = "genotype", fill = "genotype"))+
  scale_x_continuous(breaks = c(0,24,48,72,96))+
  geom_line(size = 2)+
  geom_ribbon(alpha = 0.3, color = NA)+
  theme_bw()+
  labs(y = "Necrotic pixel proportion", x = "Hours post infection")+
  theme(legend.position=c(0.12, 0.75),legend.title=element_text(size=14),
        legend.background = element_blank(),
        legend.box.background = element_blank())


#export data
require(gridExtra)
cairo_pdf("rgb_gam_beta.pdf", width = 12, height = 3.5)
grid.arrange(p.rgb.1, p.rgb.2, p.rgb.3, ncol = 3)
dev.off()


# Check residuals ---------------------------------------------------------

#Healthy
df.h.r = df11_hl
df.h.r$fit = fitted(m.g.h.1)
df.h.r$res = resid(m.g.h.1)

df.h.r %>%
  ggplot(aes(hpi, res))+
  geom_point()+
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3))

#chlorotic
df.c.r = df11_cl
df.c.r$fit = fitted(m.g.c.1)
df.c.r$res = resid(m.g.c.1)

df.c.r %>%
  ggplot(aes(hpi, res))+
  geom_point()+
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3))

#Necrotic
df.n.r = df11_nc
df.n.r$fit = fitted(m.g.n.1)
df.n.r$res = resid(m.g.n.1)

df.n.r %>%
  ggplot(aes(hpi, res))+
  geom_point()+
  stat_smooth(method = "gam", formula = y ~ s(x, k = 3))



# programming to calculate individual lines significance ------------------

require(broom)

#Healthy
output = as_tibble(setNames(data.frame(matrix(ncol = 4, nrow = 0)), c("geno", "aic1", "aic2", "aic_diff"))) #create an empty output file

#function aic diff
modf = function(i) {
  z = df11_hl %>%
    filter(genotype == "Col-0" | genotype == i) %>%
    droplevels()
  
  m1 = gam(size ~ s(hpi, k = 4) + s(hpi, leaf_id, bs = "re"), data = z, family = "betar")
  m2 = gam(size ~ s(hpi, by = genotype, k = 4) + s(hpi, leaf_id, bs = "re") + genotype, data = z, family = "betar")
  
  aic = c(AIC(m1), AIC(m2))
  
  output <<- bind_rows(output, tibble(geno = i, aic1 = AIC(m1), aic2 = AIC(m2), 
                                      aic_diff = min(aic) - max(aic)))
}


#create a genotype list
gen = c('lacs', 'cyp')

#get aic diff
map(gen, modf)

write_csv(output, "healthy_stats_aic.csv")

#Chlorotic
output = as_tibble(setNames(data.frame(matrix(ncol = 4, nrow = 0)), c("geno", "aic1", "aic2", "aic_diff"))) #create an empty output file

#function for aic
modf = function(i) {
  z = df11_cl %>%
    filter(genotype == "Col-0" | genotype == i) %>%
    droplevels()
  
  m1 = gam(size ~ s(hpi, k = 4) + s(hpi, leaf_id, bs = "re"), data = z, family = "betar")
  m2 = gam(size ~ s(hpi, by = genotype, k = 4) + s(hpi, leaf_id, bs = "re") + genotype, data = z, family = "betar")
  
  aic = c(AIC(m1), AIC(m2))
  
  output <<- bind_rows(output, tibble(geno = i, aic1 = AIC(m1), aic2 = AIC(m2), 
                                      aic_diff = min(aic) - max(aic)))
}

#get aic
map(gen, modf)

#export
write.csv(output, "chlorotic_stats_aic.csv")

#Necrotic
output = as_tibble(setNames(data.frame(matrix(ncol = 4, nrow = 0)), c("geno", "aic1", "aic2", "aic_diff"))) #create an empty output file

#function for aic
modf = function(i) {
  z = df11_nc %>%
    filter(genotype == "Col-0" | genotype == i) %>%
    droplevels()
  
  m1 = gam(size ~ s(hpi, k = 4) + s(hpi, leaf_id, bs = "re"), data = z, family = "betar")
  m2 = gam(size ~ s(hpi, by = genotype, k = 4) + s(hpi, leaf_id, bs = "re") + genotype, data = z, family = "betar")
  
  aic = c(AIC(m1), AIC(m2))
  
  output <<- bind_rows(output, tibble(geno = i, aic1 = AIC(m1), aic2 = AIC(m2), 
                                      aic_diff = (min(aic) - max(aic))))
}

#get aic
map(gen, modf)

#export
write.csv(output, "necrotic_stats_aic.csv")


#Figure 5----------------------------------------------

#dataframe with only col and lacs
dat1 = df11_hl %>% 
  filter(genotype %in% c('Col-0', 'lacs'))

#fit models
base = gam(size ~ s(hpi, k = 4) + s(hpi, leaf_id, bs = "re"), data = dat1, family = "betar")
mod1 = gam(size ~ s(hpi, by = genotype, k = 4) + s(hpi, leaf_id, bs = "re") + genotype, data = dat1, family = "betar")

#create newdata for base model
newdata = dat1 %>% 
  select(hpi, leaf_id) %>%
  filter(hpi == 0) %>%
  select(-hpi) %>% 
  slice(rep(row_number(), 31)) %>%
  mutate(hpi = rep(seq(0,96,3.2), each = 24))

#predict base model
prd.base = predict.gam(base, newdata = newdata, se.fit = T,  exclude = "s(hpi, leaf_id)", type = "response")

#bind predicted data to newdata for base model
prd.base2 = newdata

prd.base2$size_prd = prd.base$fit
prd.base2$se = prd.base$se.fit

#summarize to remove repeated data generated 
#by omitting and calculate confidence intervals for base model
prd.base3 = prd.base2 %>%
  group_by(hpi) %>%
  summarize(size = mean(size_prd), se = mean(se)) %>%
  mutate(up = size + se*1.96, low = size - se*1.96)

#create newdata for mod1
newdata = dat1 %>% 
  select(hpi, genotype, leaf_id) %>%
  filter(hpi == 0) %>%
  select(-hpi) %>% 
  slice(rep(row_number(), 31)) %>%
  mutate(hpi = rep(seq(0,96,3.2), each = 24))

#predict base model
prd.mod1 = predict.gam(mod1, newdata = newdata, se.fit = T,  exclude = "s(hpi, leaf_id)", type = "response")

#bind predicted data to newdata for base model
prd.mod1.2 = newdata

prd.mod1.2$size_prd = prd.mod1$fit
prd.mod1.2$se = prd.mod1$se.fit

#summarize to remove repeated data generated 
#by omitting and calculate confidence intervals for base model
prd.mod1.3 = prd.mod1.2 %>%
  group_by(hpi, genotype) %>%
  summarize(size = mean(size_prd), se = mean(se)) %>%
  mutate(up = size + se*1.96, low = size - se*1.96)
## create plots
p1 = dat1 %>% 
  ggplot(aes(hpi, size))+
  scale_x_continuous(breaks = c(0,24,48,72,96))+
  geom_point()+
  geom_line(aes(hpi, size), size = 2, data = prd.base3)+
  geom_ribbon(aes(hpi, ymin = low, ymax = up), size = 2, data = prd.base3, alpha = 0.3, fill = 'black')+
  theme_bw()+
  labs(y = "Chlorotic pixel proportion", x = "Hours post infection")+
  theme(legend.position=c(0.12, 0.3),legend.title=element_text(size=14),
        legend.background = element_blank(),
        legend.box.background = element_blank())


p2 = dat1 %>% 
  ggplot()+
  scale_x_continuous(breaks = c(0,24,48,72,96))+
  geom_point(aes(hpi, size, color = genotype))+
  geom_line(aes(hpi, size, color = genotype), size = 2, data = prd.mod1.3)+
  geom_ribbon(aes(hpi, ymin = low, ymax = up, fill = genotype), size = 2, data = prd.mod1.3, alpha = 0.3)+
  theme_bw()+
  labs(y = "Chlorotic pixel proportion", x = "Hours post infection")+
  theme(legend.position=c(0.12, 0.3),legend.title=element_text(size=14),
        legend.background = element_blank(),
        legend.box.background = element_blank())

#export plots
require(gridExtra)
cairo_pdf('figure_5.pdf', width = 10, height = 4)
grid.arrange(p1, p2, ncol = 2)
dev.off()
